- name: install apache2
  #  remote_user: ling
  #  hosts: webserver
  #  become: true
  #  become_user: root
  #  gather_facts: true
  #  tasks:
  #   - name: "install apache2"
  apt: name=apache2 update_cache=yes state=latest
- name: "Install php"
  apt: name=php update_cache=yes state=latest
